<?php
require 'config.php'; require 'csrf.php'; require_once 'helpers.php'; require_once 'emails.php';
$room_id=(int)($_GET['room_id']??$_POST['room_id']??0);
$stmt=$conn->prepare('SELECT * FROM rooms WHERE id=? AND is_active=1'); $stmt->bind_param('i',$room_id); $stmt->execute(); $r=$stmt->get_result()->fetch_assoc(); if(!$r) die('Room not found.');
$check_in=$_POST['check_in']??$_GET['check_in']??''; $check_out=$_POST['check_out']??$_GET['check_out']??''; $guests=max(1,(int)($_POST['guests']??$_GET['guests']??2)); $children=max(0,(int)($_POST['children']??0)); $seniors=max(0,(int)($_POST['seniors']??0)); $special=trim($_POST['special_requests']??''); $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_verify()) $error='Your session expired, please try again.'; else {
  $name=trim($_POST['guest_name']??''); $email=trim($_POST['email']??''); $phone=trim($_POST['phone']??''); $inTs=$check_in?strtotime($check_in):0; $outTs=$check_out?strtotime($check_out):0; $nights=($inTs&&$outTs)?(int)(($outTs-$inTs)/86400):0; $party=$guests+$children+$seniors;
  if(!$name||!filter_var($email,FILTER_VALIDATE_EMAIL)||!$check_in||!$check_out||$inTs<strtotime(date('Y-m-d'))||$outTs<=$inTs||$nights>30||$party>(int)$r['max_guests']) $error=$inTs<strtotime(date('Y-m-d'))?'Check-in must be today or a future date.':($nights>30?'Stays are limited to 30 nights.':($party>(int)$r['max_guests']?"This room accommodates up to {$r['max_guests']} guests including children and seniors.":'Please complete the form with valid dates.'));
  else { $q=$conn->prepare("SELECT COUNT(*) c FROM bookings WHERE room_id=? AND status!='Cancelled' AND (payment_status<>'Unpaid' OR expires_at IS NULL OR expires_at>NOW()) AND check_in<? AND check_out>?"); $q->bind_param('iss',$room_id,$check_out,$check_in); $q->execute(); if((int)$q->get_result()->fetch_assoc()['c']) $error='Sorry, this room is not available for the selected dates.'; else { $reference='LRC-'.date('Y').'-'.strtoupper(substr(str_replace(['+','/','='],'',base64_encode(random_bytes(5))),0,5)); $price=(float)$r['price']; $total=$price*$nights; $q=$conn->prepare("INSERT INTO bookings(room_id,guest_name,email,phone,check_in,check_out,guests,children,seniors,special_requests,booking_reference,price_per_night,total_amount,status,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'Pending',DATE_ADD(NOW(),INTERVAL 30 MINUTE))"); $q->bind_param('isssssiiissdd',$room_id,$name,$email,$phone,$check_in,$check_out,$guests,$children,$seniors,$special,$reference,$price,$total); $q->execute(); $id=$conn->insert_id; $q=$conn->prepare("INSERT INTO status_history(booking_id,status,payment_status,changed_by) VALUES(?,?,?,?)"); $pay='Unpaid'; $who='guest'; $state='Pending'; $q->bind_param('isss',$id,$state,$pay,$who); $q->execute(); try{send_booking_received($conn,$id);}catch(Throwable $e){error_log($e->getMessage());} header('Location: payment.php?id='.$id.'&t='.booking_token($id)); exit; } }
 }
}
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Reserve | LORENCE</title><link rel="stylesheet" href="css/style.css"></head><body><header class="nav dark"><a class="logo" href="index.php">LORENCE <span>GRAND HOTEL</span></a><nav class="site-nav"><a data-nav="home" href="index.php">Home</a><a data-nav="rooms" href="rooms.php">Rooms</a><a data-nav="amenities" href="index.php#amenities">Amenities</a><a data-nav="experience" href="index.php#experience">Experience</a><a data-nav="contact" href="index.php#contact">Contact</a></nav></header>
<main class="booking-page"><div class="booking-summary"><div class="room-image" style="background-image:url('<?=h($r['image'])?>')"></div><p class="eyebrow"><?=h($r['category'])?></p><h1><?=h($r['name'])?></h1><p><?=h($r['description'])?></p><p class="muted">Up to <?=h($r['max_guests'])?> guests, including children and seniors.</p><h3><?=peso((float)$r['price'])?> / night</h3></div><form class="booking-form" method="post"><h2>Your Reservation</h2><?php if($error):?><div class="error"><?=h($error)?></div><?php endif;?><?=csrf_field()?><input type="hidden" name="room_id" value="<?=$r['id']?>"><label>FULL NAME<input name="guest_name" required value="<?=h($_POST['guest_name']??'')?>"></label><label>EMAIL<input type="email" name="email" required value="<?=h($_POST['email']??'')?>"></label><label>PHONE NUMBER<input name="phone" required value="<?=h($_POST['phone']??'')?>"></label><div class="form-row"><label>CHECK-IN<input type="date" name="check_in" min="<?=date('Y-m-d')?>" value="<?=h($check_in)?>" required></label><label>CHECK-OUT<input type="date" name="check_out" min="<?=h($check_in?:date('Y-m-d'))?>" value="<?=h($check_out)?>" required></label></div><div class="form-row"><label>ADULT GUESTS<select name="guests" required><?php for($i=1;$i<=10;$i++):?><option value="<?=$i?>" <?=$i===$guests?'selected':''?>><?=$i?> adult<?=$i>1?'s':''?></option><?php endfor;?></select></label><label>CHILDREN<input type="number" name="children" min="0" max="20" value="<?=h($children)?>"></label></div><div class="form-row"><label>SENIOR CITIZENS<input type="number" name="seniors" min="0" max="20" value="<?=h($seniors)?>"></label><label>SPECIAL SERVICES<textarea name="special_requests" rows="2" placeholder="Accessibility, cot, assistance, or other needs"><?=h($special)?></textarea></label></div><p class="form-help">Maximum capacity: <?=h($r['max_guests'])?> people total. Your reservation is held for 30 minutes while payment is completed.</p><button class="btn-reserve full" type="submit">CONFIRM RESERVATION <span>→</span></button></form></main><script src="js/spatial.js" defer></script></body></html>
