<?php
require 'config.php'; require 'csrf.php'; require 'helpers.php';
$id=(int)($_GET['id']??0); $token=$_GET['t']??'';
if(!booking_token_verify($id,$token)){http_response_code(403);die("You don't have access to this reservation.");}
$b=fetch_booking($conn,$id); if(!$b)die('Booking not found.');
$paid=$b['payment_status']==='Paid'; $unpaid=$b['payment_status']==='Unpaid';
$eyebrow=$paid?'PAYMENT RECEIVED':($unpaid?'RESERVATION RECEIVED':'PAYMENT UNDER REVIEW');
$lead=$paid?'Your stay is confirmed. Your invoice is ready to download, and a copy was emailed to you.':($unpaid?'Your room is held. Complete payment to confirm your stay.':'We received your payment reference. Your booking number is active while our team verifies the payment. Your downloadable invoice will be released immediately after confirmation.');
?><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Confirmation | LORENCE</title><link rel="stylesheet" href="css/style.css"></head><body><main class="confirmation"><p class="eyebrow"><?=$eyebrow?></p><h1>Thank you, <?=h($b['guest_name'])?>.</h1><p><?=h($lead)?></p><div class="confirm-card"><p>BOOKING NUMBER</p><h2><?=h(booking_ref($b))?></h2><div class="confirm-grid"><span>Check-in<br><b><?=h($b['check_in'])?></b></span><span>Check-out<br><b><?=h($b['check_out'])?></b></span><span>Guests<br><b><?=h((int)$b['guests']+(int)$b['children']+(int)$b['seniors'])?></b></span><span>Status<br><b><?=h($b['status'])?></b></span><span>Payment Method<br><b><?=h($b['payment_method']??'—')?></b></span><span>Payment Reference<br><b><?=h($b['payment_reference']??'—')?></b></span><span>Payment Status<br><b><?=h($b['payment_status'])?></b></span><span>Total<br><b><?=peso(booking_total($b))?></b></span></div></div><div class="confirm-actions"><?php if($paid):?><a class="btn" href="invoice.php?id=<?=$id?>&t=<?=h(urlencode($token))?>">VIEW / DOWNLOAD INVOICE</a><?php endif;?><?php if($unpaid):?><a class="btn" href="payment.php?id=<?=$id?>&t=<?=h(urlencode($token))?>">COMPLETE PAYMENT</a><?php endif;?><a class="btn btn-ghost" href="tracking.php">TRACK BY BOOKING NUMBER</a><a class="btn btn-ghost" href="index.php">RETURN HOME</a></div></main><script src="js/spatial.js" defer></script></body></html>
