<?php
require_once __DIR__.'/../config.php'; require_once __DIR__.'/../csrf.php'; require_once __DIR__.'/../helpers.php'; require_once __DIR__.'/../payments.php';
if(session_status()===PHP_SESSION_NONE) session_start();
if(empty($_SESSION['lorence_admin'])){header('Location: login.php');exit;}
$message='';
if($_SERVER['REQUEST_METHOD']==='POST'&&csrf_verify()){
 $id=(int)($_POST['id']??0); $action=$_POST['action']??'';
 if($id&&$action==='paid'){ $ok=mark_booking_paid($conn,$id,'Manual verification',trim($_POST['reference']??'')); $message=$ok?'Booking marked paid.':'Booking was already paid or could not be updated.'; if($ok){$q=$conn->prepare("INSERT INTO status_history(booking_id,status,payment_status,changed_by) SELECT id,status,payment_status,? FROM bookings WHERE id=?");$who=$_SESSION['admin_user']??'admin';$q->bind_param('si',$who,$id);$q->execute();} }
 if($id&&$action==='cancel'){ $q=$conn->prepare("UPDATE bookings SET status='Cancelled' WHERE id=? AND status<>'Cancelled'");$q->bind_param('i',$id);$q->execute();if($q->affected_rows){$q=$conn->prepare("INSERT INTO status_history(booking_id,status,payment_status,changed_by) SELECT id,status,payment_status,? FROM bookings WHERE id=?");$who=$_SESSION['admin_user']??'admin';$q->bind_param('si',$who,$id);$q->execute();$message='Booking cancelled.';} }
}
$filter=$_GET['payment_status']??''; $where=$filter?'WHERE b.payment_status=?':''; $q=$conn->prepare("SELECT b.*,r.name room_name FROM bookings b JOIN rooms r ON r.id=b.room_id $where ORDER BY b.created_at DESC");if($filter)$q->bind_param('s',$filter);$q->execute();$bookings=$q->get_result();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin | LORENCE</title><link rel="stylesheet" href="../css/style.css"></head><body><header class="nav dark"><a class="logo" href="../index.php">LORENCE <span>STAFF CONSOLE</span></a><nav><a href="?payment_status=Pending Verification">Pending</a><a href="?payment_status=Paid">Paid</a><a href="rooms.php">Manage rooms</a><a href="logout.php">Sign out</a></nav></header><main class="admin-page"><div class="page-title"><p class="eyebrow">FRONT DESK</p><h1>Reservations</h1><p>Verify manual payments, release holds, and keep the booking ledger current.</p></div><?php if($message):?><div class="notice"><?=h($message)?></div><?php endif;?><div class="admin-table"><table><thead><tr><th>Reference</th><th>Guest / room</th><th>Stay</th><th>Total</th><th>Status</th><th>Action</th></tr></thead><tbody><?php while($b=$bookings->fetch_assoc()):?><tr><td><b><?=h(booking_ref($b))?></b><small><?=h($b['email'])?></small></td><td><?=h($b['guest_name'])?><small><?=h($b['room_name'])?></small></td><td><?=h($b['check_in'])?> → <?=h($b['check_out'])?><small><?=h($b['guests']+$b['children']+$b['seniors'])?> guests</small></td><td><?=peso((float)$b['total_amount'])?></td><td><span class="status"><?=h($b['payment_status'])?></span><small><?=h($b['status'])?></small></td><td><?php if($b['payment_status']==='Pending Verification'):?><form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="id" value="<?=$b['id']?>"><input type="hidden" name="action" value="paid"><input name="reference" placeholder="Ref (optional)"><button class="btn btn-small" type="submit">MARK PAID</button></form><?php endif;?><?php if($b['status']!=='Cancelled'):?><form method="post" class="inline-form"><?=csrf_field()?><input type="hidden" name="id" value="<?=$b['id']?>"><input type="hidden" name="action" value="cancel"><button class="btn btn-small btn-danger" type="submit">CANCEL</button></form><?php endif;?></td></tr><?php endwhile;?></tbody></table></div></main></body></html>
